---
title: "Interactive Review Graphics"
author: "Veronica Pagowski"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Spatial Disjunctions

```{r eval =TRUE, echo=FALSE, message = FALSE, warning = FALSE }
setwd("~/Desktop/Review")
ref_data <- read.csv("rayyan_references_included_chords2.csv", header = TRUE)

###Associations plots
library(tidyverse)
library(chorddiag)
library(htmlwidgets)
library(gdata)
library(htmltools)
df<- read.csv("articles.csv", header = TRUE)
df<-df %>% 
  filter(str_detect(Category, pattern = "nogap",negate=TRUE))

############## SMALL SPATIAL SCALES ONLY ##############
dfs<-df %>% 
  filter(str_detect(Category, pattern = "J"))
#Spatial = S, Community = C, Genetic = G
# Small-scale = J, Big = K

#Get spatial gap matrix
spatial1<-dfs %>% 
  filter(str_detect(Category, pattern = "S") & !str_detect(Category, pattern = "G"))
out_spatial1 <- crossprod(table(subset(stack(setNames(lapply(strsplit(spatial1$Category, 
                                                                      "[][]|,\\s*"), trimws), spatial1$Id))[2:1], nzchar(values))))
diag(out_spatial1) <- 0
#remove U and M category (misc. and unknown)
out_spatial1 <- out_spatial1[, !colnames(out_spatial1) %in% c("U","M")] 
out_spatial1 <- out_spatial1[!rownames(out_spatial1) %in% c("U","M"),]

#Arrange 
custom_order<-c("V","O","H","I","E","B","T","C","S")
out_spatial1 <- out_spatial1[custom_order, custom_order]
out_spatial1[upper.tri(out_spatial1)] <- NA
upperTriangle(out_spatial1) = lowerTriangle(out_spatial1, byrow=TRUE)

#get genetic gap matrix
genetic1<-dfs %>% 
  filter(str_detect(Category, pattern = "G") & !str_detect(Category, pattern = "S"))
out_gen1 <- crossprod(table(subset(stack(setNames(lapply(strsplit(genetic1$Category,  "[][]|,\\s*"), trimws), genetic1$Id))[2:1], nzchar(values))))
diag(out_gen1) <- 0
out_gen1 <- out_gen1[, !colnames(out_gen1) %in% c("U","M")] 
out_gen1 <- out_gen1[!rownames(out_gen1) %in% c("U","M"),]
#Arrange 
custom_order<-c("V","O","H","I","L","B","T","F","G")
out_gen1 <- out_gen1[custom_order, custom_order]
out_gen1[upper.tri(out_gen1)] <- NA
upperTriangle(out_gen1) = lowerTriangle(out_gen1, byrow=TRUE)


cols <- c(B = "indianred3", C = "darkmagenta", E = "#F0E442",
            "F" = "#6EE2FF", G = "darkblue",
            H = "violetred", I = "brown4",
            L = "royalblue3",M = "yellow4",
            O = "olivedrab2",S = "gray25",
            Sx = "lightsalmon","T" = "#009E73",
            U = "tan",V = "plum1",W = "chocolate1")


#Make interactive plots


##Spatial
#add white columns that are blank to spatially separate diagram
cols_s <- c("#FFBBFF","#B3EE3A","#D02090","#8B2323", "#F0E442","#CD5555", "#009E73","white","white","white","white","white","white","#8B008B","#404040","white","white","white","white","white","white")

ad <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
out_spatial2 = cbind(out_spatial1[,c(1:7)],ad,ad,ad,ad,ad,ad,out_spatial1[,c(8:9)],ad,ad,ad,ad,ad,ad)
out_spatial2 = rbind(out_spatial2[c(1:7),],ad,ad,ad,ad,ad,ad,out_spatial2[c(8:9),],ad,ad,ad,ad,ad,ad)

p <- chorddiag(out_spatial2, groupColors = cols_s, showGroupnames = FALSE,groupPadding = 2,showTooltips = FALSE,tickInterval=10,ticklabelFontsize=0)
#p

##Genetic
#add white columns that are blank to spatially separate diagram
cols_g <- c("#FFBBFF","#B3EE3A","#D02090","#8B2323", "#3A5FCD", "#CD5555","#009E73","#6EE2FF", "white","white","white","white","white","white","#00008B","white","white","white","white","white","white")
ad <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
out_gen2 = cbind(out_gen1[,c(1:8)],ad,ad,ad,ad,ad,ad,out_gen1[,c(9)],ad,ad,ad,ad,ad,ad)
out_gen2 = rbind(out_gen2[c(1:8),],ad,ad,ad,ad,ad,ad,out_gen2[c(9),],ad,ad,ad,ad,ad,ad)

q <- chorddiag(out_gen2, groupColors = cols_g, showGroupnames = FALSE,groupPadding = 2,showTooltips = FALSE,tickInterval=10,ticklabelFontsize=0)
#q


layout <- div(style = "display: flex; flex-direction: row;",p,q)

# Embed the layout into an HTML page
layout
setwd("/Users/veronicapagowski/Desktop/interactive_app/interactive_review")
#save_html(layout, "chorddiag_plots.html")

#saveWidget(p, "chord_test.html", selfcontained = TRUE, knitrOptions = list())
#saveWidget(p, "chord_test2.html", selfcontained = TRUE, knitrOptions = list())

```